/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ecommerce;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author bashi
 */
public class EditProfile extends javax.swing.JFrame {

    /**
     * Creates new form EditProfile
     */
    public EditProfile() {
        initComponents();
        jPanel1.setBackground(new Color(0,0,0,130));
        Connect();
    }
    String name;
    Connection con;
    PreparedStatement ps;
    ResultSet rs;
    boolean Signin;
    
    public EditProfile(String ID, String name, boolean Signin){
        initComponents();
         this.name=name;
         this.Signin=Signin;
         Connect();
         try{
             
             String sql = "select * from user where name = ?";
             ps= con.prepareStatement(sql);
             ps.setString(1,name);
             
             ResultSet rs = ps.executeQuery();
             
             if(rs.next()){
                 jTextFieldUsername.setText(rs.getString("name"));
                 jTextFieldPhone.setText(rs.getString("phone"));
                 jTextFieldEmail.setText(rs.getString("email"));
                 jTextFieldAddress.setText(rs.getString("address"));
             }
             this.setVisible(false);
                    userpage u=new userpage(name,Signin);
                    u.setVisible(true);
         }
         catch (SQLException ex) {
            Logger.getLogger(userlogin.class.getName()).log(Level.SEVERE, null, ex);
           }
         
    }
    
    public void Connect()
    {
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/ecommerce","root","anjum2000");
        }
        catch(ClassNotFoundException ex)
        {
            Logger.getLogger(userlogin.class.getName()).log(Level.SEVERE,null,ex);
        }
        catch(SQLException ex)
        {
            Logger.getLogger(userlogin.class.getName()).log(Level.SEVERE,null,ex);
        }
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        Phone = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jTextFieldPhone = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldAddress = new javax.swing.JTextField();
        UpdateButton = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        NameValidationLabel = new javax.swing.JLabel();
        PhoneValidationLabel = new javax.swing.JLabel();
        EmailValidationLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 575));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EDIT PROFILE");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 10, 247, 43);

        Username.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setText("User Name");
        jPanel1.add(Username);
        Username.setBounds(30, 90, 110, 26);

        Phone.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        Phone.setForeground(new java.awt.Color(255, 255, 255));
        Phone.setText("Phone");
        jPanel1.add(Phone);
        Phone.setBounds(50, 160, 60, 26);

        Email.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setText("Email");
        jPanel1.add(Email);
        Email.setBounds(50, 230, 60, 26);

        Address.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        Address.setForeground(new java.awt.Color(255, 255, 255));
        Address.setText("Address");
        jPanel1.add(Address);
        Address.setBounds(40, 290, 71, 26);

        jTextFieldUsername.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldUsernameKeyReleased(evt);
            }
        });
        jPanel1.add(jTextFieldUsername);
        jTextFieldUsername.setBounds(160, 80, 221, 36);

        jTextFieldPhone.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPhoneKeyReleased(evt);
            }
        });
        jPanel1.add(jTextFieldPhone);
        jTextFieldPhone.setBounds(160, 150, 221, 36);

        jTextFieldEmail.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldEmailKeyReleased(evt);
            }
        });
        jPanel1.add(jTextFieldEmail);
        jTextFieldEmail.setBounds(160, 220, 221, 36);

        jTextFieldAddress.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(jTextFieldAddress);
        jTextFieldAddress.setBounds(160, 290, 221, 36);

        UpdateButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        UpdateButton.setText("Update");
        UpdateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateButton);
        UpdateButton.setBounds(30, 360, 80, 25);

        Cancel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Cancel.setText("Cancel");
        Cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        jPanel1.add(Cancel);
        Cancel.setBounds(300, 360, 71, 25);

        DeleteButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        DeleteButton.setText("Delete Account");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteButton);
        DeleteButton.setBounds(140, 360, 130, 25);

        NameValidationLabel.setBackground(new java.awt.Color(0, 102, 153));
        NameValidationLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NameValidationLabel.setForeground(new java.awt.Color(255, 0, 0));
        NameValidationLabel.setOpaque(true);
        jPanel1.add(NameValidationLabel);
        NameValidationLabel.setBounds(160, 120, 220, 27);

        PhoneValidationLabel.setBackground(new java.awt.Color(0, 102, 153));
        PhoneValidationLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PhoneValidationLabel.setForeground(new java.awt.Color(255, 0, 0));
        PhoneValidationLabel.setOpaque(true);
        jPanel1.add(PhoneValidationLabel);
        PhoneValidationLabel.setBounds(160, 190, 220, 27);

        EmailValidationLabel.setBackground(new java.awt.Color(0, 102, 153));
        EmailValidationLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        EmailValidationLabel.setForeground(new java.awt.Color(255, 0, 0));
        EmailValidationLabel.setOpaque(true);
        jPanel1.add(EmailValidationLabel);
        EmailValidationLabel.setBounds(160, 260, 220, 27);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(340, 130, 410, 410);
        jPanel1.setBackground(new Color(0,0,0,130));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 3, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setText("SHOPPER'S STALL");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(310, 30, 460, 67);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\bashi\\OneDrive\\Desktop\\Ruzaina Files\\DBMS Project\\Icons and images\\register blue background 1 resized 11.jpg")); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 1100, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        new userpage(name,Signin).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CancelActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        try{
            Connect();
            String sql = "update user set name = ?, phone = ?, email = ?, address = ? where name = ?";
            ps= con.prepareStatement(sql);
            
            ps.setString(1, jTextFieldUsername.getText());
            ps.setString(2, jTextFieldPhone.getText());
            ps.setString(3, jTextFieldEmail.getText());
            ps.setString(4, jTextFieldAddress.getText());
            ps.setString(5,name);
            
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"Update Successful !!!");
        }
        catch(SQLException ex)
        {
            Logger.getLogger(userlogin.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        try{
            Connect();
            String sql = "delete from user where name = ?";
            ps= con.prepareStatement(sql);
            ps.setString(1,name);
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"Account deleted Successfully !");
            
            Signin=false;
            this.setVisible(false);
            userpage u = new userpage("",Signin);
            u.setVisible(true);
        } 
        catch(SQLException ex)
        {
            Logger.getLogger(userlogin.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void jTextFieldUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldUsernameKeyReleased
        // TODO add your handling code here:
        String PATTERN ="^[a-zA-Z\\s]{0,120}$";//"^[A-Za-z]+[ '-][A-Za-z][ '-][A-Za-z]+{0,120}$";//[A-Z]+([ '-][a-zA-Z]+)
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(jTextFieldUsername.getText());
        if(!match.matches())
        {
            NameValidationLabel.setText("Name is Invalid!");
            
        }
        else 
        {
            NameValidationLabel.setText(null);

        }
    }//GEN-LAST:event_jTextFieldUsernameKeyReleased

    private void jTextFieldPhoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPhoneKeyReleased
        // TODO add your handling code here:
        String PATTERN ="^[0-9]{10}$";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(jTextFieldPhone.getText());
        if(!match.matches())
        {
            PhoneValidationLabel.setText("Phone number is invalid!");
        }
        else
        {
            PhoneValidationLabel.setText(null);
        }
    }//GEN-LAST:event_jTextFieldPhoneKeyReleased

    private void jTextFieldEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmailKeyReleased
        // TODO add your handling code here:
         String PATTERN ="^[a-zA-Z0-9._+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}$";//"^[a-zA-Z0-9]{0,30}@[a-zA-Z0-9]{0,10}[.][a-zA-Z]{0,5}$";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(jTextFieldEmail.getText());
        if(!match.matches())
        {
            EmailValidationLabel.setText("Email Is Invalid!");
        }
        else 
        {
            EmailValidationLabel.setText(null);
        }
    }//GEN-LAST:event_jTextFieldEmailKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JButton Cancel;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel EmailValidationLabel;
    private javax.swing.JLabel NameValidationLabel;
    private javax.swing.JLabel Phone;
    private javax.swing.JLabel PhoneValidationLabel;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldPhone;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
