/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ecommerce;
import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/**
 *
 * @author bashi
 */
public class HouseholdAndKitchen extends javax.swing.JInternalFrame {

    /**
     * Creates new form HouseholdAndKitchen
     */
    /*public HouseholdAndKitchen() {
        initComponents();
        Connect();
        JTable();
    }*/
    
    Connection con;
    PreparedStatement ps; 
    ResultSet rs;
    boolean Signin;
    String role;
    String name;
    String Category="Household and Kitchen Appliances";
    int CID=2;
    String ID;
    
    
public HouseholdAndKitchen(String name,boolean Signin) {
        
        initComponents(); 
      Connect();
      this.name=name;
      this.Signin=Signin;
      JTable();
    }

    public HouseholdAndKitchen(String id,String name,boolean Signin) {
        
        initComponents(); 
      Connect();
      this.name=name;
      this.Signin=Signin;
      this.ID=id;
       //JTable.setBackground(new Color(231, 76, 60, 50));
      JTable();
      
    }

   public void Connect()
    {
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/ecommerce","root","anjum2000");
        }
        catch(ClassNotFoundException ex)
        {
            Logger.getLogger(userlogin.class.getName()).log(Level.SEVERE,null,ex);
        }
        catch(SQLException ex)
        {
            Logger.getLogger(userlogin.class.getName()).log(Level.SEVERE,null,ex);
        }
    }
  
     public void JTable()
    {
        JTable.getColumnModel().getColumn(0).setPreferredWidth(0);
          JTable.getColumnModel().getColumn(1).setPreferredWidth(300);
         JTable.getColumnModel().getColumn(2).setPreferredWidth(1000);
         JTable.getColumnModel().getColumn(3).setPreferredWidth(200);
         JTable.getColumnModel().getColumn(4).setPreferredWidth(0);
         //Color background=new Color(0,0,0,0);

        try
        {                      
           ps=con.prepareStatement("select * from products where category=?");
           ps.setString(1,Category);
           rs=ps.executeQuery();
           
           ResultSetMetaData Rsm=rs.getMetaData();
           int c;
           c=Rsm.getColumnCount();
           
           DefaultTableModel d1=(DefaultTableModel)JTable.getModel();
           d1.setRowCount(0);
           
           while(rs.next())
           {
               Vector v2=new Vector();
               for(int i=1;i<=c;i++)
               {
                   v2.add(rs.getInt("p_id"));
                   v2.add(rs.getString("p_name"));
                   v2.add(rs.getString("description"));
                   v2.add(rs.getInt("price"));
                   v2.add(rs.getString("pathname"));

                   
               }
               d1.addRow(v2);
               
           }
        } catch (SQLException ex) {
            Logger.getLogger(HouseholdAndKitchen.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setAutoscrolls(true);
        setMinimumSize(new java.awt.Dimension(1116, 547));
        setPreferredSize(new java.awt.Dimension(1116, 547));
        getContentPane().setLayout(null);

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        jDesktopPane1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 195, 452, 331);

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 0, 0, 0);

        JTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "P_id", "Product Name", "Description", "Price", "Photo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTable.setShowHorizontalLines(false);
        JTable.setShowVerticalLines(false);
        JTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(JTable);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(0, 240, 1110, 320);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setText("Best Deals On");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 20, 170, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 51));
        jLabel2.setText("Household And Kitchen Appliances");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(290, 40, 370, 43);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\bashi\\OneDrive\\Desktop\\Ruzaina Files\\DBMS Project\\Icons and images\\Categories\\Household and kitchen appliances 3 resized.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1100, 240);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    addMA row_data=new addMA(name,Signin,CID,Category);
    SelectedRow data=new SelectedRow(name,Signin,CID,Category);
    
    private void JTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableMouseClicked
        // TODO add your handling code here:
        if(name.equals("Ruksar") || name.equals("Ruzaina"))
      {
            int index=JTable.getSelectedRow();
            TableModel model=JTable.getModel();
            String PID=model.getValueAt(index,0).toString();
            String ProductName=model.getValueAt(index,1).toString();
            String Description=model.getValueAt(index,2).toString();
            String Price=model.getValueAt(index,3).toString();
            filename=model.getValueAt(index,4).toString();

            
            this.setVisible(false);
            row_data.setVisible(true);
            row_data.pack();
            row_data.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            row_data.AddProductButton.setEnabled(false);
            row_data.jLabel7.setText(name);
            row_data.jLabel5.setText(ID);
            row_data.jLabel6.setText(PID);
            row_data.pname.setText(ProductName);
            row_data.desc.setText(Description);
            row_data.cost.setText(Price);
            ImageIcon imageicon=new ImageIcon(model.getValueAt(index,4).toString());
              //Resize image to fit jLabel
            Image imageFit = imageicon.getImage().getScaledInstance(row_data.pic.getWidth(),row_data.pic.getHeight(),Image.SCALE_SMOOTH);
            row_data.pic.setIcon(new ImageIcon(imageFit));
            row_data.pic.setText("");
            row_data.path.setText(filename);

      }
       
     else
      {
          int index=JTable.getSelectedRow();
            TableModel model=JTable.getModel();
            String PID=model.getValueAt(index,0).toString();
            String ProductName=model.getValueAt(index,1).toString();
            String Description=model.getValueAt(index,2).toString();
            String Price=model.getValueAt(index,3).toString();
            
            
            data.setVisible(true);
            data.pack();
            data.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            data.jLabel6.setText(ID);
            data.jLabel7.setText(PID);
            data.jLabel8.setText(Price);
            data.pname.setText(ProductName);
            data.desc.setText(Description);
            data.cost.setText(Price);
            ImageIcon imageicon=new ImageIcon(model.getValueAt(index,4).toString());
              //Resize image to fit jLabel
            Image imageFit = imageicon.getImage().getScaledInstance(data.pic.getWidth(),data.pic.getHeight(),Image.SCALE_SMOOTH);
            data.pic.setIcon(new ImageIcon(imageFit));

            
      }
    }//GEN-LAST:event_JTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTable;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables

byte[] photo=null;
String filename=null;
}