/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ecommerce;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;


/**
 *
 * @author bashi
 */
public class SelectedRow extends javax.swing.JFrame {

    /**
     * Creates new form SelectedRow
     */
    public SelectedRow() {
        initComponents();
        Connect();
        jPanel1.setBackground(new Color(248,38,19,120));
        //jPanel1.setBackground(new Color(240,52,52,150));

    }
    
     Connection con;
    PreparedStatement ps; 
    ResultSet rs;
    String Category;
    int CID;
    String Name;
    String Role;
    boolean Signin;
    String ID;
    String productName;

    
    public SelectedRow(String name,boolean Signin,int CID,String Category) {
         initComponents();
        Connect();
        jPanel1.setBackground(new Color(248,38,19,150));
        this.Name=name;
        this.Signin=Signin;
        this.CID=CID;
        this.Category=Category;
        productName=pname.getText();
        ID=jLabel6.getText();
        

    }
    
    public void Connect()
      {
          try{
              Class.forName("com.mysql.cj.jdbc.Driver");
              con = DriverManager.getConnection("jdbc:mysql://localhost/ecommerce","root","anjum2000");
              }
          catch(ClassNotFoundException ex)
              {Logger.getLogger(userlogin.class.getName()).log(Level.SEVERE, null, ex);
               }
          catch (SQLException ex) {
            Logger.getLogger(userlogin.class.getName()).log(Level.SEVERE, null, ex);
             }
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AddToCart = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        cost = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        desc = new javax.swing.JTextArea();
        pname = new javax.swing.JTextField();
        pic = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1138, 575));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Product Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(26, 42, 107, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Description");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(26, 150, 107, 24);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Price");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(26, 219, 107, 29);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Quantity");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(26, 274, 107, 30);

        AddToCart.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        AddToCart.setText("Add To Cart");
        AddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToCartActionPerformed(evt);
            }
        });
        jPanel1.add(AddToCart);
        AddToCart.setBounds(211, 343, 140, 29);

        Cancel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        jPanel1.add(Cancel);
        Cancel.setBounds(470, 340, 100, 29);

        jSpinner1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        jPanel1.add(jSpinner1);
        jSpinner1.setBounds(143, 272, 85, 30);
        jPanel1.add(cost);
        cost.setBounds(140, 220, 296, 29);

        desc.setColumns(20);
        desc.setRows(5);
        jScrollPane1.setViewportView(desc);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(140, 100, 296, 76);
        jPanel1.add(pname);
        pname.setBounds(140, 40, 296, 30);
        jPanel1.add(pic);
        pic.setBounds(490, 50, 260, 270);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        jPanel1.add(jDesktopPane2);
        jDesktopPane2.setBounds(490, 50, 260, 270);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(160, 80, 800, 390);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(240, 40, 80, 30);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(430, 40, 80, 30);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(650, 40, 70, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\bashi\\OneDrive\\Desktop\\Ruzaina Files\\DBMS Project\\Icons and images\\Backdrops\\addma selected row resized.jpeg")); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1100, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToCartActionPerformed
        // TODO add your handling code here:
            //if(Signin==true)
    //{
      
      String productName=pname.getText();
      int Quantity=Integer.parseInt(jSpinner1.getValue().toString());
      int Price=Integer.parseInt(cost.getText());
      int uid=Integer.parseInt(jLabel6.getText());
      int pid=Integer.parseInt(jLabel7.getText());
      int totprice=Integer.parseInt(jLabel8.getText());
        try{
             ps=con.prepareStatement("insert into cart(u_id,p_id,p_name,quantity,price,totalPrice)values(?,?,?,?,?,?)");
            
             ps.setInt(1,uid);
             ps.setInt(2,pid);
             ps.setString(3,productName);
             ps.setInt(4,Quantity);
             ps.setInt(5,Price);
             ps.setInt(6,totprice);
            
             ps.executeUpdate();
             
             //JOptionPane.showMessageDialog(this,"Product added to cart!");
             //this.setVisible(false);
             
             ps=con.prepareStatement("insert into cart1(u_id,p_id,p_name,quantity,price,totalPrice)values(?,?,?,?,?,?)");
            
             ps.setInt(1,uid);
             ps.setInt(2,pid);
             ps.setString(3,productName);
             ps.setInt(4,Quantity);
             ps.setInt(5,Price);
             ps.setInt(6,totprice);
            
             ps.executeUpdate();
             
             JOptionPane.showMessageDialog(this,"Product added to cart!");
             this.setVisible(false);
           }
        catch (SQLException ex) {
            Logger.getLogger(userlogin.class.getName()).log(Level.SEVERE, null, ex);
           }
         //}
        
    /*else
    {
        JOptionPane.showMessageDialog(this,"You are not signed in!!!!Please sign in first");
    }*/

    
        
        
                                            
    /*else
    {
        JOptionPane.showMessageDialog(this,"You are not signed in!  Please sign in first");
    }*/
    }//GEN-LAST:event_AddToCartActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
     /*   if(Category=="Mobiles and Accessories")
     {
        MobilesAndAccessories ma=new MobilesAndAccessories(Name,Signin);
        ma.setVisible(true);
        this.setVisible(false);
     }
        else if(Category=="Household and Kitchen Appliances")
     {
        HouseholdAndKitchen hk=new HouseholdAndKitchen(Name,Signin);
        hk.setVisible(true);
        this.setVisible(false);
    } 
     else if(Category=="Grocery")
     {
        Groceries g=new Groceries(Name,Signin);
        g.setVisible(true);
        this.setVisible(false);
    }
     else if(Category=="Furniture")
     {
         Furniture f = new Furniture(Name,Signin);
         f.setVisible(true);
         this.setVisible(false);
     }
     else if(Category=="Books and Stationery")
     {
         BooksAndStationery b=new BooksAndStationery(Name,Signin);
         b.setVisible(true);
         this.setVisible(false);
     }
     else if(Category=="Daily Essentials")
     {
         DailyEssentials de=new DailyEssentials(Name,Signin);
         de.setVisible(true);
         this.setVisible(false);
     }*/
    }//GEN-LAST:event_CancelActionPerformed

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:
                int Quantity=Integer.parseInt(jSpinner1.getValue().toString());
        int Price=Integer.parseInt(cost.getText().toString());
        int tot=Price * Quantity;
        jLabel8.setText(String.valueOf(tot));

    }//GEN-LAST:event_jSpinner1StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectedRow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectedRow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectedRow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectedRow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectedRow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddToCart;
    private javax.swing.JButton Cancel;
    public javax.swing.JTextField cost;
    public javax.swing.JTextArea desc;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    public javax.swing.JLabel pic;
    public javax.swing.JTextField pname;
    // End of variables declaration//GEN-END:variables
}
