/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ecommerce;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/**
 *
 * @author bashi
 */
public class ViewOrders extends javax.swing.JFrame {

    /**
     * Creates new form ViewOrders
     */
    public ViewOrders() {
        initComponents();
        Connect();
        ordersTable();
        ordersTable.setBackground(new Color(137, 196, 244, 1));
    }
Connection con;
 PreparedStatement ps; 
 ResultSet rs;
 String ID;
 String Name;
 boolean Signin;

    public void Connect()
      {
          try{
              Class.forName("com.mysql.cj.jdbc.Driver");
              con = DriverManager.getConnection("jdbc:mysql://localhost/ecommerce","root","anjum2000");
              }
          catch(ClassNotFoundException ex)
              {Logger.getLogger(userlogin.class.getName()).log(Level.SEVERE, null, ex);
               }
          catch (SQLException ex) {
            Logger.getLogger(userlogin.class.getName()).log(Level.SEVERE, null, ex);
             }
      }
    
    
    public void ordersTable()
     {
         
         
 DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
 centerRenderer.setHorizontalAlignment(JLabel.CENTER);
 ordersTable.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
 ordersTable.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
 ordersTable.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
 ordersTable.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
 
 ordersTable.getColumnModel().getColumn(0).setPreferredWidth(80);
 ordersTable.getColumnModel().getColumn(1).setPreferredWidth(80);
 ordersTable.getColumnModel().getColumn(2).setPreferredWidth(100);
 ordersTable.getColumnModel().getColumn(3).setPreferredWidth(300);
       
         try
        {                      
           ps=con.prepareStatement("select * from orders");
          
           rs=ps.executeQuery();
           
           ResultSetMetaData Rsm=rs.getMetaData();
           int c;
           c=Rsm.getColumnCount();
           
           DefaultTableModel d1=(DefaultTableModel)ordersTable.getModel();
           d1.setRowCount(0);
           
           while(rs.next())
           {
              
               Vector v2=new Vector();
               for(int i=1;i<=c;i++)
               {
                   v2.add(rs.getInt("order_id"));
                   v2.add(rs.getInt("u_id"));
                   v2.add(rs.getDate("date"));
                   v2.add(rs.getString("address"));
               }
               d1.addRow(v2);
               
           }
        } catch (SQLException ex) {
            Logger.getLogger(MobilesAndAccessories.class.getName()).log(Level.SEVERE, null, ex);
        } 
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ordersTable = new javax.swing.JTable();
        Close = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(850, 400));
        setMinimumSize(new java.awt.Dimension(850, 400));

        jPanel1.setMaximumSize(new java.awt.Dimension(850, 400));
        jPanel1.setMinimumSize(new java.awt.Dimension(850, 400));
        jPanel1.setLayout(null);

        ordersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order ID", "Customer ID", "Date", "Address"
            }
        ));
        ordersTable.setShowHorizontalLines(false);
        ordersTable.setShowVerticalLines(false);
        ordersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ordersTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ordersTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(8, 11, 530, 290);

        Close.setBackground(new java.awt.Color(204, 204, 255));
        Close.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Close.setText("Close");
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });
        jPanel1.add(Close);
        Close.setBounds(20, 310, 90, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\bashi\\OneDrive\\Desktop\\Ruzaina Files\\DBMS Project\\Icons and images\\Backdrops\\ViewOrders.jpeg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 850, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ordersTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordersTableMouseClicked
        // TODO add your handling code here:
 int index=ordersTable.getSelectedRow();
 TableModel model=ordersTable.getModel();
 String Order_ID=model.getValueAt(index,0).toString();
 int Customer_ID=Integer.parseInt(model.getValueAt(index,1).toString());
 //jLabel1.setText(model.getValueAt(index,1).toString());
 //int user_id=Integer.parseInt(jLabel1.getText());
 Order1 or=new Order1(Customer_ID);
 
 or.jTextField1.setText(Order_ID);
 or.jTextField2.setText(model.getValueAt(index,1).toString());
 or.setVisible(true);
    }//GEN-LAST:event_ordersTableMouseClicked

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_CloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewOrders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable ordersTable;
    // End of variables declaration//GEN-END:variables
}
